//! New action type system with strongly typed generics.
//!
//! This module provides a trait-based action system where:
//! - `L1Action` trait: for actions signed via connection_id mechanism
//! - `UserSignedAction` trait: for actions signed via EIP-712 typed data
//! - `Action` trait: unified interface auto-implemented for both
//! - `SignedAction<T>`: strongly typed signed action ready to submit

use serde::de::DeserializeOwned;
use serde_json::Value;

mod core;
mod l1_actions;
mod multisig;
mod serialization;
mod signing;
mod traits;
mod user_signed_actions;

pub use core::{PreparedAction, SignedAction, SignedActionKind};
pub use l1_actions::*;
pub use multisig::{
    assemble_signed_multisig_action, build_multisig_action, multisig_inner_signing_hash,
    multisig_inner_user_signed_signing_hash, multisig_outer_signing_hash, MultiSigAction,
    MultiSigPayload, MultisigSigningHashes, MultiSigSigningPayload, SignedMultiSigAction,
};
pub use traits::{Action, L1Action, UserSignedAction};
pub use user_signed_actions::*;

pub(crate) use serialization::{build_action_value, build_multisig_inner_action_value};
pub(crate) use serialization::L1ActionWrapper;
pub(crate) use signing::{agent_signing_hash, compute_l1_hash, SigningMeta};

/// Macro that generates both the `ActionKind` enum and the runtime dispatcher.
///
/// When adding a new action, just add it to the list. The dispatcher automatically
/// determines how to match each action based on its trait constants:
///
/// - **Flatten types** (`action_type == payload_key`): matched by unique `action_type`
/// - **Sum types** (`action_type != payload_key`): matched by `action_type` + `payload_key`
///
/// Sum types (like perpDeploy, spotDeploy) share the same `action_type` but are
/// discriminated by which `payload_key` is present in the JSON object.
macro_rules! impl_action_kind {
    ($($action:ident),* $(,)?) => {
        #[derive(Debug, Clone)]
        pub enum ActionKind {
            $($action($action),)*
            /// Fallback for forward-compatibility when we don't recognize `action.type`
            /// or its payload shape yet.
            Unknown {
                action_type: String,
                raw: Value,
            },
        }

        /// Dispatch a JSON action object to the appropriate `ActionKind` variant.
        ///
        /// This is generated by the `impl_action_kind!` macro and used by
        /// `SignedActionKind` deserialization.
        ///
        /// Dispatch logic:
        /// - **Flatten types** (`action_type == payload_key`): unique action_type,
        ///   return immediately on match
        /// - **Sum types** (`action_type != payload_key`): collect all matches where
        ///   both action_type AND payload_key match, then validate exactly one matched
        pub(crate) fn dispatch_action_kind<E: serde::de::Error>(
            obj: &serde_json::Map<String, serde_json::Value>,
        ) -> Result<ActionKind, E> {
            let action_type = obj
                .get("type")
                .and_then(|v| v.as_str())
                .ok_or_else(|| E::custom("missing action type"))?;

            // Collect sum type matches (action_type != payload_key)
            // Flatten types return immediately since their action_type is unique
            let mut sum_type_matches: Vec<ActionKind> = Vec::new();

            $(
                if action_type == <$action as Action>::ACTION_TYPE {
                    let is_flatten = <$action as Action>::ACTION_TYPE == <$action as Action>::PAYLOAD_KEY;
                    if is_flatten {
                        // Flatten type: unique action_type, return immediately
                        return Ok(ActionKind::$action(parse_action::<$action, E>(obj)?));
                    } else if obj.contains_key(<$action as Action>::PAYLOAD_KEY) {
                        // Sum type: matched both action_type and payload_key
                        sum_type_matches.push(ActionKind::$action(parse_action::<$action, E>(obj)?));
                    }
                }
            )*

            // Handle sum type results
            match sum_type_matches.len() {
                1 => Ok(sum_type_matches.into_iter().next().unwrap()),
                0 => Ok(ActionKind::Unknown {
                    action_type: action_type.to_string(),
                    raw: serde_json::Value::Object(obj.clone()),
                }),
                _ => Err(E::custom(format!(
                    "ambiguous action type '{}' (multiple payload keys present)",
                    action_type
                ))),
            }
        }

        /// Helper to parse an action from a JSON object using the shared extraction logic.
        fn parse_action<T, E>(obj: &serde_json::Map<String, serde_json::Value>) -> Result<T, E>
        where
            T: Action + DeserializeOwned,
            E: serde::de::Error,
        {
            serialization::parse_action_from_obj(obj)
        }
    };
}

impl_action_kind![
    // User-signed actions (flatten types)
    UsdSend,
    Withdraw,
    SpotTransfer,
    UsdClassTransfer,
    SendAsset,
    UserDexAbstraction,
    UserSetAbstraction,
    TokenDelegate,
    ConvertToMultiSigUser,
    ApproveAgent,
    ApproveBuilderFee,
    // L1 actions (flatten types)
    ToggleBigBlocks,
    NoOp,
    ClaimRewards,
    SetReferrer,
    CreateSubAccount,
    SubAccountTransfer,
    SubAccountSpotTransfer,
    VaultTransfer,
    AgentEnableDexAbstraction,
    FinalizeEvmContract,
    // Trading actions
    UpdateLeverage,
    UpdateIsolatedMargin,
    ScheduleCancel,
    // Sum types: order actions (action_type = "order"/"cancel"/etc, payload_key varies)
    BatchOrder,
    BatchCancel,
    CancelByCloid,
    BatchModify,
    // Sum types: perpDeploy (action_type = "perpDeploy", payload_key varies)
    RegisterAsset,
    SetOpenInterestCaps,
    ToggleTrading,
    SetOracle,
    SetFeeRecipient,
    SetFeeScale,
    SetFundingMultipliers,
    SetFundingInterestRates,
    SetMarginTableIds,
    InsertMarginTable,
    MigrateDexQuoteToken,
    DisableDex,
    SetSubDeployers,
    SetGrowthModes,
    SetMarginModes,
    SetPerpAnnotation,
    // Sum types: spotDeploy (action_type = "spotDeploy", payload_key varies)
    RegisterToken,
    Genesis,
    UserGenesis,
    RegisterSpot,
    RegisterHyperliquidity,
    SetDeployerFees,
    RequestEvmContract,
    EnableFreezePrivilege,
    FreezeUser,
    RevokeFreezePrivilege,
    EnableQuoteToken,
];
